id: I361AD8AA
ocr_import_info:
  bdrc_scan_id: W1KG22609
  source: bdrc
  ocr_info:
    timestamp: '2022-08-25T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-01-21 16:21:17.500023
last_modified: 2022-08-25 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22609
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22609
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་དགོངས་པ་ཡང་ཟབ་ཀྱི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས།
  languages:
  - bo
  author: རྒྱལ་དབང་རིན་ཆེན་ཕུན་ཚོགས།
bases:
  I1KG22617:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22617
      total_pages: 510
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG22617.txt
    order: 1
  I1KG22622:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22622
      total_pages: 476
      volume_number: 6
      volume_pages_bdrc_intro: 2
    base_file: I1KG22622.txt
    order: 2
  I1KG22623:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22623
      total_pages: 336
      volume_number: 7
      volume_pages_bdrc_intro: 2
    base_file: I1KG22623.txt
    order: 3
  I1KG22621:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22621
      total_pages: 586
      volume_number: 5
      volume_pages_bdrc_intro: 2
    base_file: I1KG22621.txt
    order: 4
  I1KG22620:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22620
      total_pages: 594
      volume_number: 4
      volume_pages_bdrc_intro: 2
    base_file: I1KG22620.txt
    order: 5
  I1KG22624:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22624
      total_pages: 200
      volume_number: 8
      volume_pages_bdrc_intro: 2
    base_file: I1KG22624.txt
    order: 6
  I1KG22618:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22618
      total_pages: 880
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I1KG22618.txt
    order: 7
  I1KG22619:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22619
      total_pages: 570
      volume_number: 3
      volume_pages_bdrc_intro: 2
    base_file: I1KG22619.txt
    order: 8
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
